# Pipeline to deploy the FnT Web app to the stage environment. The FnT web app points to the Optimizely DXP Integration environment



trigger:
- QA_Sprint4.0

pr: # Trigger on pull requests towards branches
- QA_Sprint4.0

#schedules:
#- cron: "30 11 * * 0-6"
#  displayName: Schedule build1 at 5PM
#  branches:
#   include:
#    - develop
#  always: true

#- cron: "30 15 * * 0-6"
#  displayName: Schedule build2 at 9PM
#  branches:
#   include:
#    - develop
#  always: true

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'foster-thrive-service-connection'

  # Web app name
  webAppName: 'foster-thrive-stg'
  
  # Environment name
  environmentName: 'stg'

  # Agent VM image name
  vmImageName: 'windows-2019'

stages:
- stage: Build
  displayName: Build UI Web App stage
  jobs:
  - job: Build
    displayName: Build UI Web App
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    
    - task: CmdLine@2
      inputs:
        script: |
          cat next.config.js
          mv config/env.stg.next.config.js next.config.js
          sleep 3s
          printf "Stage url updated"
          cat next.config.js
      displayName: 'Stage Url updation'

    - task: CmdLine@2
      inputs:
        script: 'npm install'
      displayName: 'npm install'

    - task: CmdLine@2
      inputs:
        script: 'npm run build'
      displayName: 'npm build'    

    #- task: CmdLine@2
    #  inputs:
    #    script: 'npm run test --if-present'
    #  displayName: 'npm test'
    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

#    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#      artifact: drop 
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'Artifact_Foster_ThriveQA'
        publishLocation: 'Container'

