# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 - release/*

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'foster-thrive-service-connection'

  # Web app name
  webAppName1: 'foster-thrive-dev'
  webAppName2: 'foster-thrive-stg'

  # Environment name
  environmentName1: 'dev'
  environmentName2: 'stg'

  # Agent VM image name
  vmImageName: 'windows-2019'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm build:stg
        npm run test --if-present
      displayName: 'npm install, build and test'


- stage: StageApproval
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 180 # job times out in 3 hours
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 180 # task times out 3 hours
        inputs:
          notifyUsers: |
           ambika.r@photon.com
          instructions: 'Please approve'
          onTimeout:  'resume'
- stage: staging_Deploy
  displayName: Deploy staging
  dependsOn: StageApproval
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: staging Deploy
    environment: $(environmentName2)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'foster-thrive-service-connection'
              appType: 'webApp'
              WebAppName: 'foster-thrive-stg'
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
 