import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/header";
import Footer from "@/components/footer";

import NavBar from "@/components/navbar";
import CarouselComponent from "@/components/carousel";
import CategoryComponent from "@/components/category";
import LearningSectionComponent from "@/components/learning_section";

export default function Home() {
  return (
    <>
      <Head>
        <title>McKession</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <NavBar />
      <CarouselComponent />
      <div className={styles.bodyContainer + " " + "container"}>
        <CategoryComponent />
        <LearningSectionComponent />
      </div>

      <Footer />
    </>
  );
}
